name: compressao
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Marcelo - Dell <marcelo68ms@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  archive: ^2.0.8
  path: ^1.6.2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
