// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFosphe9r_0wIKLAj489bQEduLLAQdgl0',
    appId: '1:802793673553:web:6210ca4164a2774e5af970',
    messagingSenderId: '802793673553',
    projectId: 'felicitatem-5224a',
    authDomain: 'felicitatem-5224a.firebaseapp.com',
    storageBucket: 'felicitatem-5224a.appspot.com',
    measurementId: 'G-TRZCCX17YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDydFElX6YZvxVaLJFqidP5D6JqsbmMHMo',
    appId: '1:802793673553:android:49a1f1e531f6192a5af970',
    messagingSenderId: '802793673553',
    projectId: 'felicitatem-5224a',
    storageBucket: 'felicitatem-5224a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIrjKwJHbSv4TpbwXZHBX1f_WgugUICls',
    appId: '1:802793673553:ios:62a45a056a764cf65af970',
    messagingSenderId: '802793673553',
    projectId: 'felicitatem-5224a',
    storageBucket: 'felicitatem-5224a.appspot.com',
    iosClientId: '802793673553-au0m5fsdvjgbioshj8li4b9j7in2grtb.apps.googleusercontent.com',
    iosBundleId: 'com.example.usoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIrjKwJHbSv4TpbwXZHBX1f_WgugUICls',
    appId: '1:802793673553:ios:62a45a056a764cf65af970',
    messagingSenderId: '802793673553',
    projectId: 'felicitatem-5224a',
    storageBucket: 'felicitatem-5224a.appspot.com',
    iosClientId: '802793673553-au0m5fsdvjgbioshj8li4b9j7in2grtb.apps.googleusercontent.com',
    iosBundleId: 'com.example.usoFirebase',
  );
}
