// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVxO8VE7p9X_vgIFTtygUFidS683maBXY',
    appId: '1:805610606949:web:fbb31d2bff4b7755a6d18c',
    messagingSenderId: '805610606949',
    projectId: 'curso-firebase-webapps-9781e',
    authDomain: 'curso-firebase-webapps-9781e.firebaseapp.com',
    databaseURL: 'https://curso-firebase-webapps-9781e.firebaseio.com',
    storageBucket: 'curso-firebase-webapps-9781e.appspot.com',
    measurementId: 'G-XGM351RE6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH4hmEYxoQHPpo6CyWoJQVUr6ruoPzKzI',
    appId: '1:805610606949:android:c4c41f2daf58307fa6d18c',
    messagingSenderId: '805610606949',
    projectId: 'curso-firebase-webapps-9781e',
    databaseURL: 'https://curso-firebase-webapps-9781e.firebaseio.com',
    storageBucket: 'curso-firebase-webapps-9781e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeoMs90_Avp1g-F7RxY2uzURfZmo-uJyQ',
    appId: '1:805610606949:ios:5ba2c75da8d943b6a6d18c',
    messagingSenderId: '805610606949',
    projectId: 'curso-firebase-webapps-9781e',
    databaseURL: 'https://curso-firebase-webapps-9781e.firebaseio.com',
    storageBucket: 'curso-firebase-webapps-9781e.appspot.com',
    iosClientId: '805610606949-ltmsoqio44tkn34pkfnf2h9rla4s4qvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeoMs90_Avp1g-F7RxY2uzURfZmo-uJyQ',
    appId: '1:805610606949:ios:5ba2c75da8d943b6a6d18c',
    messagingSenderId: '805610606949',
    projectId: 'curso-firebase-webapps-9781e',
    databaseURL: 'https://curso-firebase-webapps-9781e.firebaseio.com',
    storageBucket: 'curso-firebase-webapps-9781e.appspot.com',
    iosClientId: '805610606949-ltmsoqio44tkn34pkfnf2h9rla4s4qvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebase',
  );
}
